@startuml
namespace controller {
    class CLIController << (S,Aquamarine) >> {
        - logger zerolog.Logger

        + HandleStartCLI(address string) 

    }
    class TCPController << (S,Aquamarine) >> {
        - logger zerolog.Logger
        - address string
        - port string
        - db *memdb.DB

        + HandleStartTCPServer() 

    }
    class WebUIController << (S,Aquamarine) >> {
        - logger zerolog.Logger
        - port string
        - db *memdb.DB

        + HandleStart() 

    }
}


"controller.CLIController""uses" o-- "zerolog.Logger"
"controller.TCPController""uses" o-- "memdb.DB"
"controller.TCPController""uses" o-- "zerolog.Logger"
"controller.WebUIController""uses" o-- "memdb.DB"
"controller.WebUIController""uses" o-- "zerolog.Logger"

namespace memdb {
    class DB << (S,Aquamarine) >> {
        - logger zerolog.Logger

        + Mutex *sync.RWMutex
        + Records <font color=blue>map</font>[string]Value

        + List() <font color=blue>map</font>[string]Value
        + Set(key string, value string, expire time.Duration) Value
        + Get(key string) ([]byte, bool)
        + Del(key string) bool

    }
    interface DBI  {
        + List() <font color=blue>map</font>[string]Value
        + Set(key string, value string, expire time.Duration) Value
        + Get(key string) ([]byte, bool)
        + Del(key string) bool

    }
    class MockDB << (S,Aquamarine) >> {
        + Records <font color=blue>map</font>[string]Value

        + List() <font color=blue>map</font>[string]Value
        + Set(key string, value string, expire time.Duration) Value
        + Get(key string) ([]byte, bool)
        + Del(key string) bool

    }
    class Value << (S,Aquamarine) >> {
        + Created time.Time
        + Expiry time.Duration
        + Data []byte

    }
}

"memdb.DBI" <|-- "implements""memdb.DB"
"memdb.DBI" <|-- "implements""memdb.MockDB"

"memdb.DB""uses" o-- "memdb.Value"
"memdb.DB""uses" o-- "sync.RWMutex"
"memdb.DB""uses" o-- "zerolog.Logger"
"memdb.MockDB""uses" o-- "memdb.Value"
"memdb.Value""uses" o-- "time.Duration"
"memdb.Value""uses" o-- "time.Time"

namespace tcp {
    class Command << (S,Aquamarine) >> {
        + Value string
        + Args []string
        + Conn net.Conn

    }
    interface CommandHandlerI  {
        + Handle(cmd Command, s *Server) 

    }
    class DelCommandHandler << (S,Aquamarine) >> {
        + Handle(cmd Command, s *Server) 

    }
    class GetCommandHandler << (S,Aquamarine) >> {
        + Handle(cmd Command, s *Server) 

    }
    class ListCommandHandler << (S,Aquamarine) >> {
        + Handle(cmd Command, s *Server) 

    }
    class MockConn << (S,Aquamarine) >> {
        - readBuffer *bytes.Buffer
        - writeBuffer *bytes.Buffer

        + Read(b []byte) (int, error)
        + Write(b []byte) (int, error)
        + Close() error
        + LocalAddr() net.Addr
        + RemoteAddr() net.Addr
        + SetDeadline(t time.Time) error
        + SetReadDeadline(t time.Time) error
        + SetWriteDeadline(t time.Time) error
        + GetWrittenData() string

    }
    class Server << (S,Aquamarine) >> {
        - logger zerolog.Logger
        - address string
        - listener net.Listener
        - commands <font color=blue>chan</font> Command

        + DB memdb.DBI

        + ReadCommand(conn net.Conn) 
        + WriteCommand(conn net.Conn, data string) 
        + HandleCommand() 
        + Start() 
        + HandleConnections() 

    }
    class SetCommandHandler << (S,Aquamarine) >> {
        + Handle(cmd Command, s *Server) 

    }
}

"tcp.CommandHandlerI" <|-- "implements""tcp.DelCommandHandler"
"tcp.CommandHandlerI" <|-- "implements""tcp.GetCommandHandler"
"tcp.CommandHandlerI" <|-- "implements""tcp.ListCommandHandler"
"tcp.CommandHandlerI" <|-- "implements""tcp.SetCommandHandler"

"tcp.Command""uses" o-- "net.Conn"
"tcp.MockConn""uses" o-- "bytes.Buffer"
"tcp.Server""uses" o-- "memdb.DBI"
"tcp.Server""uses" o-- "net.Listener"
"tcp.Server""uses" o-- "tcp.Command"
"tcp.Server""uses" o-- "zerolog.Logger"

@enduml
